### ISSUE TITLE
Implement Hot Reloader

### ISSUE THREAD

**Issue by Kodemon** [reach/react#3]
For live updates using BrowserSync

http://www.slant.co/topics/1479/compare/~browsersync_vs_codekit_vs_livereload

I think browsersync might be easier and more flexible than livereload.

**Comment by mattgi** [comment]
Look at webpacks hot reloader. It's better than the others

**Comment by mattgi** [comment]
http://benfletcher.com/article/Webpack-vs-Browserify-for-React/

The hot loading part is that it's like a swap for just the changed module, not the entire UI

**Comment by Kodemon** [comment]
@mattgi can you look at this?
